### ISSUE TITLE
PHP 7.3(.1) Error - 502 Bad gateway - PHP-FPM exited on signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by xopez** [Newcomer1989/TSN-Ranksystem#572]
Hallo,

ich habe auf PHP 7.3 umgestellt und bekomme nun manchmal den Fehler 503. Glaube aktuell kaum, dass es durch das ranksystem ausgelöst wird, aber es passiert komischerweise nur auf der einen Subdomain.
Mit PHP 7.2 hatte ich keine Probleme. Vielleicht hat hier jemand einen Plan.
OS: ‪Ubuntu 16.04.5 LTS‬
Produkt: Plesk Onyx 17.8.11 Update Nr. 36
Sowohl mit PHP 7.3 als auch 7.3.1 was heute kam.
Auch hier wurde das Thema schonmal aufgegriffen:
https://community.woltlab.com/thread/273968-502-bad-gateway-nach-umstellung-auf-php-7-3-0/
und hier:
https://talk.plesk.com/threads/php-7-3-fpm-dies-without-a-trace.350761/

Jedoch ist es nicht der gleiche Fehler.
Wäre dankbar über Hilfe.

Passiert immer beim Login im Webinterface, sprich Daten eingeben und einloggen. Dann kommt der Fehler. Man klickt auf reload und es geht. Sporadisch passiert das auch mal beim restarten des Bots.

error_log
```
[Mon Jan 14 18:38:56.085594 2019] [proxy_fcgi:error] [pid 32356] [client 5.57.199.231:52400] AH01067: Failed to read FastCGI header, referer: https://rank.mightful-noobs.de/webinterface/
[Mon Jan 14 18:38:56.085683 2019] [proxy_fcgi:error] [pid 32356] (104)Connection reset by peer: [client 5.57.199.231:52400] AH01075: Error dispatching request to : , referer: https://rank.mightful-noobs.de/webinterface/
[Mon Jan 14 18:39:42.402330 2019] [proxy_fcgi:error] [pid 32353] [client 5.57.199.231:52449] AH01067: Failed to read FastCGI header, referer: https://rank.mightful-noobs.de/webinterface/
[Mon Jan 14 18:39:42.402381 2019] [proxy_fcgi:error] [pid 32353] (104)Connection reset by peer: [client 5.57.199.231:52449] AH01075: Error dispatching request to : , referer: https://rank.mightful-noobs.de/webinterface/
[Mon Jan 14 18:40:34.102331 2019] [proxy_fcgi:error] [pid 32353] [client 5.57.199.231:52484] AH01067: Failed to read FastCGI header, referer: https://rank.mightful-noobs.de/webinterface/
[Mon Jan 14 18:40:34.102378 2019] [proxy_fcgi:error] [pid 32353] (104)Connection reset by peer: [client 5.57.199.231:52484] AH01075: Error dispat
ching request to : , referer: https://rank.mightful-noobs.de/webinterface/
```

```
/var/log/plesk-php73-fpm/error.log
[13-Jan-2019 06:33:33] NOTICE: error log file re-opened
[13-Jan-2019 10:42:48] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[13-Jan-2019 10:42:48] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[13-Jan-2019 10:42:49] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[13-Jan-2019 10:42:49] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[13-Jan-2019 10:42:49] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[13-Jan-2019 10:42:49] NOTICE: Terminating ...
[13-Jan-2019 10:42:49] NOTICE: exiting, bye-bye!
[13-Jan-2019 10:42:49] NOTICE: fpm is running, pid 18066
[13-Jan-2019 10:42:49] NOTICE: ready to handle connections
[13-Jan-2019 10:42:49] NOTICE: systemd monitor interval set to 10000ms
[13-Jan-2019 11:13:56] WARNING: [pool rank.mightful-noobs.de] child 26265 said into stderr: "zend_mm_heap corrupted"
[13-Jan-2019 11:13:56] WARNING: [pool rank.mightful-noobs.de] child 26265 exited with code 1 after 15.938161 seconds from start
[13-Jan-2019 11:13:56] NOTICE: [pool rank.mightful-noobs.de] child 26266 started
[13-Jan-2019 18:48:12] WARNING: [pool mightful-noobs.de] child 12652 said into stderr: "  "
[13-Jan-2019 20:33:22] WARNING: [pool ts3bridge.mightful-noobs.de] child 11180 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: invalid clientID in /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TeamSpeak3/Node/Server.php:782"
[13-Jan-2019 20:33:22] WARNING: [pool ts3bridge.mightful-noobs.de] child 11180 said into stderr: "Stack trace:"
[13-Jan-2019 20:33:22] WARNING: [pool ts3bridge.mightful-noobs.de] child 11180 said into stderr: "#0 /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TS3Bridge.php(128): TeamSpeak3_Node_Server->clientGetByUid('Xr+GqGkd2jfXCIB...')"
[13-Jan-2019 20:33:22] WARNING: [pool ts3bridge.mightful-noobs.de] child 11180 said into stderr: "#1 {main}"
[13-Jan-2019 20:33:22] WARNING: [pool ts3bridge.mightful-noobs.de] child 11180 said into stderr: "  thrown in /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TeamSpeak3/Node/Server.php on line 782"
[13-Jan-2019 20:33:24] WARNING: [pool ts3bridge.mightful-noobs.de] child 11188 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught TeamSpeak3_Adapter_ServerQuery_Exception: invalid clientID in /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TeamSpeak3/Node/Server.php:782"
[13-Jan-2019 20:33:24] WARNING: [pool ts3bridge.mightful-noobs.de] child 11188 said into stderr: "Stack trace:"
[13-Jan-2019 20:33:24] WARNING: [pool ts3bridge.mightful-noobs.de] child 11188 said into stderr: "#0 /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TS3Bridge.php(146): TeamSpeak3_Node_Server->clientGetByUid('Xr+GqGkd2jfXCIB...')"
[13-Jan-2019 20:33:24] WARNING: [pool ts3bridge.mightful-noobs.de] child 11188 said into stderr: "#1 {main}"
[13-Jan-2019 20:33:24] WARNING: [pool ts3bridge.mightful-noobs.de] child 11188 said into stderr: "  thrown in /var/www/vhosts/mightful-noobs.de/ts3bridge.mightful-noobs.de/TeamSpeak3/Node/Server.php on line 782"
[13-Jan-2019 20:53:40] NOTICE: fpm is running, pid 18025
[13-Jan-2019 20:53:40] NOTICE: ready to handle connections
[13-Jan-2019 20:53:40] NOTICE: systemd monitor interval set to 10000ms
[14-Jan-2019 18:38:06] NOTICE: Terminating ...
[14-Jan-2019 18:38:06] NOTICE: exiting, bye-bye!
[14-Jan-2019 18:38:06] NOTICE: fpm is running, pid 27151
[14-Jan-2019 18:38:06] NOTICE: ready to handle connections
[14-Jan-2019 18:38:06] NOTICE: systemd monitor interval set to 10000ms
[14-Jan-2019 18:38:56] WARNING: [pool rank.mightful-noobs.de] child 32361 said into stderr: "zend_mm_heap corrupted"
[14-Jan-2019 18:38:56] WARNING: [pool rank.mightful-noobs.de] child 32361 exited with code 1 after 19.376529 seconds from start
[14-Jan-2019 18:38:56] NOTICE: [pool rank.mightful-noobs.de] child 32659 started
[14-Jan-2019 18:39:42] WARNING: [pool rank.mightful-noobs.de] child 2813 said into stderr: "zend_mm_heap corrupted"
[14-Jan-2019 18:39:42] WARNING: [pool rank.mightful-noobs.de] child 2813 exited with code 1 after 29.138005 seconds from start
[14-Jan-2019 18:39:42] NOTICE: [pool rank.mightful-noobs.de] child 3898 started
[14-Jan-2019 18:40:34] WARNING: [pool rank.mightful-noobs.de] child 4752 said into stderr: "zend_mm_heap corrupted"
[14-Jan-2019 18:40:34] WARNING: [pool rank.mightful-noobs.de] child 4752 exited with code 1 after 8.699365 seconds from start
[14-Jan-2019 18:40:34] NOTICE: [pool rank.mightful-noobs.de] child 4753 started
```
error.log.1

```
[07-Jan-2019 06:31:16] NOTICE: error log file re-opened
[07-Jan-2019 14:39:25] WARNING: [pool mightful-noobs.de] child 2514 exited on signal 11 (SIGSEGV) after 0.093948 seconds from start
[07-Jan-2019 14:39:25] NOTICE: [pool mightful-noobs.de] child 2515 started
[07-Jan-2019 15:29:18] WARNING: [pool rank.mightful-noobs.de] child 14482 exited on signal 11 (SIGSEGV) after 13.946645 seconds from start
[07-Jan-2019 15:29:18] NOTICE: [pool rank.mightful-noobs.de] child 14484 started
[07-Jan-2019 15:31:27] WARNING: [pool mightful-noobs.de] child 15684 said into stderr: " "
[07-Jan-2019 15:31:42] WARNING: [pool mightful-noobs.de] child 15685 said into stderr: "NOTICE: PHP message: PHP Warning:  POST Content-Length of 12193354 bytes exceeds the limit of 8388608 bytes in Unknown on line 0"
[07-Jan-2019 15:34:14] WARNING: [pool mightful-noobs.de] child 16021 said into stderr: "NOTICE: PHP message: PHP Warning:  POST Content-Length of 12193344 bytes exceeds the limit of 8388608 bytes in Unknown on line 0"
[08-Jan-2019 08:09:43] WARNING: [pool mightful-noobs.de] child 16595 exited on signal 11 (SIGSEGV) after 0.309424 seconds from start
[08-Jan-2019 08:09:43] NOTICE: [pool mightful-noobs.de] child 16596 started
[08-Jan-2019 08:09:44] WARNING: [pool mightful-noobs.de] child 16596 exited on signal 11 (SIGSEGV) after 0.199414 seconds from start
[08-Jan-2019 08:09:44] NOTICE: [pool mightful-noobs.de] child 16597 started
[08-Jan-2019 17:01:12] WARNING: [pool mightful-noobs.de] child 20336 said into stderr: " "
[08-Jan-2019 18:11:04] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[08-Jan-2019 18:11:05] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[08-Jan-2019 18:11:05] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[08-Jan-2019 18:11:05] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[08-Jan-2019 18:11:05] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[08-Jan-2019 18:11:06] NOTICE: Terminating ...
[08-Jan-2019 18:11:06] NOTICE: exiting, bye-bye!
[08-Jan-2019 18:11:06] NOTICE: fpm is running, pid 11114
[08-Jan-2019 18:11:06] NOTICE: ready to handle connections
[08-Jan-2019 18:11:06] NOTICE: systemd monitor interval set to 10000ms
[08-Jan-2019 18:11:56] WARNING: [pool mightful-noobs.de] child 12166 said into stderr: "NOTICE: PHP message: PHP Warning:  POST Content-Length of 12193344 bytes exceeds the limit of 8388608 bytes in Unknown on line 0"
[10-Jan-2019 15:45:30] WARNING: [pool rank.mightful-noobs.de] child 2371 exited on signal 11 (SIGSEGV) after 7.448730 seconds from start
[10-Jan-2019 15:45:30] NOTICE: [pool rank.mightful-noobs.de] child 2372 started
[10-Jan-2019 17:24:48] WARNING: [pool mightful-noobs.de] child 25979 exited on signal 11 (SIGSEGV) after 0.621039 seconds from start
[10-Jan-2019 17:24:48] NOTICE: [pool mightful-noobs.de] child 25980 started
[10-Jan-2019 17:24:49] WARNING: [pool mightful-noobs.de] child 25980 exited on signal 11 (SIGSEGV) after 0.332449 seconds from start
[10-Jan-2019 17:24:49] NOTICE: [pool mightful-noobs.de] child 25981 started
[10-Jan-2019 20:53:10] WARNING: [pool mightful-noobs.de] child 11845 said into stderr: " "
[11-Jan-2019 14:45:51] WARNING: [pool rank.mightful-noobs.de] child 32420 exited on signal 11 (SIGSEGV) after 8.616470 seconds from start
[11-Jan-2019 14:45:51] NOTICE: [pool rank.mightful-noobs.de] child 32422 started
[12-Jan-2019 20:04:24] WARNING: [pool mightful-noobs.de] child 15332 said into stderr: " "
[12-Jan-2019 21:25:17] WARNING: [pool mightful-noobs.de] child 2846 exited on signal 11 (SIGSEGV) after 0.080365 seconds from start
[12-Jan-2019 21:25:17] NOTICE: [pool mightful-noobs.de] child 2847 started
[13-Jan-2019 00:14:11] WARNING: [pool mightful-noobs.de] child 13150 said into stderr: " "
```

error.log.2
```
[30-Dec-2018 06:32:15] NOTICE: error log file re-opened
[30-Dec-2018 13:43:39] WARNING: [pool mightful-noobs.de] child 2138 said into stderr: " "
[30-Dec-2018 15:09:04] WARNING: [pool rank.mightful-noobs.de] child 22612 exited on signal 11 (SIGSEGV) after 7.109208 seconds from start
[30-Dec-2018 15:09:04] NOTICE: [pool rank.mightful-noobs.de] child 22998 started
[30-Dec-2018 15:34:24] WARNING: [pool rank.mightful-noobs.de] child 29366 exited on signal 11 (SIGSEGV) after 10.504658 seconds from start
[30-Dec-2018 15:34:24] NOTICE: [pool rank.mightful-noobs.de] child 29371 started
[30-Dec-2018 15:47:58] WARNING: [pool rank.mightful-noobs.de] child 355 exited on signal 11 (SIGSEGV) after 10.220254 seconds from start
[30-Dec-2018 15:47:58] NOTICE: [pool rank.mightful-noobs.de] child 357 started
[30-Dec-2018 16:29:40] WARNING: [pool rank.mightful-noobs.de] child 10393 exited on signal 11 (SIGSEGV) after 17.135037 seconds from start
[30-Dec-2018 16:29:40] NOTICE: [pool rank.mightful-noobs.de] child 10401 started
[30-Dec-2018 16:32:27] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[30-Dec-2018 16:32:28] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[30-Dec-2018 16:32:28] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[30-Dec-2018 16:32:28] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[30-Dec-2018 16:32:29] NOTICE: configuration file /opt/plesk/php/7.3/etc/php-fpm.conf test is successful

[30-Dec-2018 16:32:29] NOTICE: Terminating ...
[30-Dec-2018 16:32:29] NOTICE: exiting, bye-bye!
[30-Dec-2018 16:32:29] NOTICE: fpm is running, pid 18634
[30-Dec-2018 16:32:29] NOTICE: ready to handle connections
[30-Dec-2018 16:32:29] NOTICE: systemd monitor interval set to 10000ms
[30-Dec-2018 20:07:49] WARNING: [pool mightful-noobs.de] child 9108 said into stderr: " "
[30-Dec-2018 20:07:49] WARNING: [pool mightful-noobs.de] child 9108 said into stderr: " "
[31-Dec-2018 11:03:18] WARNING: [pool mightful-noobs.de] child 11513 said into stderr: " "
[01-Jan-2019 14:36:56] WARNING: [pool mightful-noobs.de] server reached max_children setting (5), consider raising it
[02-Jan-2019 07:09:34] WARNING: [pool mightful-noobs.de] server reached max_children setting (5), consider raising it
[02-Jan-2019 13:15:07] WARNING: [pool mightful-noobs.de] child 28447 said into stderr: "  "
[03-Jan-2019 00:48:20] WARNING: [pool rank.mightful-noobs.de] child 4992 exited on signal 11 (SIGSEGV) after 7.948071 seconds from start
[03-Jan-2019 00:48:20] NOTICE: [pool rank.mightful-noobs.de] child 4993 started
[03-Jan-2019 00:48:33] WARNING: [pool rank.mightful-noobs.de] child 4993 exited on signal 11 (SIGSEGV) after 12.513700 seconds from start
[03-Jan-2019 00:48:33] NOTICE: [pool rank.mightful-noobs.de] child 4994 started
[03-Jan-2019 10:21:43] WARNING: [pool mightful-noobs.de] child 21162 said into stderr: " "
[03-Jan-2019 19:32:55] WARNING: [pool rank.mightful-noobs.de] child 29757 exited on signal 11 (SIGSEGV) after 23.246435 seconds from start
[03-Jan-2019 19:32:55] NOTICE: [pool rank.mightful-noobs.de] child 29772 started
[03-Jan-2019 19:40:27] WARNING: [pool rank.mightful-noobs.de] child 32112 said into stderr: "zend_mm_heap corrupted"
[03-Jan-2019 22:36:20] WARNING: [pool rank.mightful-noobs.de] child 10935 exited on signal 11 (SIGSEGV) after 3.431478 seconds from start
[03-Jan-2019 22:36:20] NOTICE: [pool rank.mightful-noobs.de] child 10936 started
[04-Jan-2019 00:39:32] WARNING: [pool rank.mightful-noobs.de] child 8341 exited on signal 11 (SIGSEGV) after 11.756888 seconds from start
[04-Jan-2019 00:39:32] NOTICE: [pool rank.mightful-noobs.de] child 8344 started
[04-Jan-2019 00:39:43] WARNING: [pool rank.mightful-noobs.de] child 8344 exited on signal 11 (SIGSEGV) after 11.089951 seconds from start
[04-Jan-2019 00:39:43] NOTICE: [pool rank.mightful-noobs.de] child 8345 started
[04-Jan-2019 00:51:07] WARNING: [pool rank.mightful-noobs.de] child 13755 exited on signal 11 (SIGSEGV) after 4.340096 seconds from start
[04-Jan-2019 00:51:07] NOTICE: [pool rank.mightful-noobs.de] child 13764 started
[04-Jan-2019 00:51:12] WARNING: [pool rank.mightful-noobs.de] child 13764 said into stderr: "zend_mm_heap corrupted"
[04-Jan-2019 00:51:12] WARNING: [pool rank.mightful-noobs.de] child 13764 exited with code 1 after 4.157051 seconds from start
[04-Jan-2019 00:51:12] NOTICE: [pool rank.mightful-noobs.de] child 13765 started
[04-Jan-2019 00:51:44] WARNING: [pool rank.mightful-noobs.de] child 13770 exited on signal 11 (SIGSEGV) after 11.009492 seconds from start
[04-Jan-2019 00:51:44] NOTICE: [pool rank.mightful-noobs.de] child 13771 started
[04-Jan-2019 00:53:55] WARNING: [pool rank.mightful-noobs.de] child 13821 exited on signal 11 (SIGSEGV) after 2.242924 seconds from start
[04-Jan-2019 00:53:55] NOTICE: [pool rank.mightful-noobs.de] child 13837 started
[04-Jan-2019 01:26:17] WARNING: [pool rank.mightful-noobs.de] child 22278 exited on signal 11 (SIGSEGV) after 2.405108 seconds from start
[04-Jan-2019 01:26:17] NOTICE: [pool rank.mightful-noobs.de] child 22294 started
[04-Jan-2019 01:44:37] WARNING: [pool rank.mightful-noobs.de] child 26781 exited on signal 11 (SIGSEGV) after 7.196039 seconds from start
[04-Jan-2019 01:44:37] NOTICE: [pool rank.mightful-noobs.de] child 26785 started
[04-Jan-2019 01:49:43] WARNING: [pool rank.mightful-noobs.de] child 29998 exited on signal 11 (SIGSEGV) after 2.530577 seconds from start
[04-Jan-2019 01:49:43] NOTICE: [pool rank.mightful-noobs.de] child 30014 started
[04-Jan-2019 01:50:02] WARNING: [pool rank.mightful-noobs.de] child 30014 said into stderr: "zend_mm_heap corrupted"
[04-Jan-2019 12:24:38] WARNING: [pool rank.mightful-noobs.de] child 32492 exited on signal 11 (SIGSEGV) after 5.626815 seconds from start
[04-Jan-2019 12:24:38] NOTICE: [pool rank.mightful-noobs.de] child 32493 started
[04-Jan-2019 12:25:30] WARNING: [pool rank.mightful-noobs.de] child 462 said into stderr: "zend_mm_heap corrupted"
[04-Jan-2019 14:08:20] WARNING: [pool rank.mightful-noobs.de] child 26208 exited on signal 11 (SIGSEGV) after 10.355682 seconds from start
[04-Jan-2019 14:08:20] NOTICE: [pool rank.mightful-noobs.de] child 26209 started
[04-Jan-2019 14:09:55] WARNING: [pool rank.mightful-noobs.de] child 26629 exited on signal 11 (SIGSEGV) after 42.554547 seconds from start
[04-Jan-2019 14:09:55] NOTICE: [pool rank.mightful-noobs.de] child 26631 started
[04-Jan-2019 21:12:08] WARNING: [pool rank.mightful-noobs.de] child 483 exited on signal 11 (SIGSEGV) after 13.947870 seconds from start
[04-Jan-2019 21:12:08] NOTICE: [pool rank.mightful-noobs.de] child 827 started
[04-Jan-2019 23:34:56] WARNING: [pool mightful-noobs.de] child 2944 said into stderr: " "
[05-Jan-2019 01:21:03] WARNING: [pool mightful-noobs.de] child 2122 exited on signal 11 (SIGSEGV) after 0.141765 seconds from start
[05-Jan-2019 01:21:03] NOTICE: [pool mightful-noobs.de] child 2126 started
[06-Jan-2019 23:09:00] WARNING: [pool mightful-noobs.de] child 23232 said into stderr: " "
```

**Comment by Newcomer1989** [comment]
This could be the same bug.. so it is still reported.

https://bugs.php.net/bug.php?id=77430

**Comment by xopez** [comment]
Scheint sich mit PHP 7.3.2 in Luft aufgelöst zu haben.
https://docs.plesk.com/release-notes/onyx/change-log/#contents-17811-mu40
Konnte bis jetzt nichts mehr feststellen.
![grafik](https://user-images.githubusercontent.com/28950736/52582843-75214a00-2e2e-11e9-8a3c-c34ea67214fc.png)

**Comment by xopez** [comment]
Ich schließ den Issue mal, da es ja seit 7.3.3 wieder sauber läuft.
