### ISSUE TITLE
Error 500 while displaying site after migrating to new webserver

### ISSUE THREAD

**Issue by Ultrashadow** [Newcomer1989/TSN-Ranksystem#831]
Hi, iam getting a http 500 message after migrating to the new server while display tsn, I already checked permissions and and have set them to similar permissions. install.php shows that it cannot run PHP, already tried it with various PHP (PHP 7.xx) I don't know anymore...

using plesk on debian 10 as system...

**Comment by Shad86** [comment]
If you're using plesk keep an eye on it that the "user:group" are fitting to the one plesk's using. I only say this because im not 100% sure if you mean with similar the plesk one's and not the one's from any tutorials, as http 500 usually means there is an permission error.

Second thing make sure (on 7.xxx) that at least this packages are available: 
`php-zip libapache2-mod-php php-curl php-xml php-mysql php-common php-mbstring php-ssh2
`
Third thing pls be sure to ONLY chmod the following folders/file:
`chmod 740 tsicons/ avatars/ logs/ update/ other/dbconfig.php -Rf`

If you not sure if you made mistakes with the chmod you may consider to delete the webserver files and try it again.

regards

Shad86

**Comment by Ultrashadow** [comment]
Hi, I did all changes and now I just get a blank page :(

at least it doesn't say HTTP 500 anymore

**Comment by Ultrashadow** [comment]
2021-08-02 21:34:09 | Warning | 5.147.48.78 | mod_fcgid: stderr: #2 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/webinterface/_preload.php(11): php_error_handling()
-- | -- | -- | --
2021-08-02 21:34:09 | Warning | 5.147.48.78 | mod_fcgid: stderr: #3 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/webinterface/index.php(2): require_once('/var/www/vhosts...')
2021-08-02 21:34:09 | Warning | 5.147.48.78 | mod_fcgid: stderr: #4 {main}
2021-08-02 21:34:09 | Warning | 5.147.48.78 | mod_fcgid: stderr:   thrown in /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php on line 43
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: PHP Notice:  Undefined index: logs_path in /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php on line 32
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: PHP Notice:  Undefined index: logs_timezone in /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php on line 43
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: PHP Fatal error:  Uncaught Exception: DateTimeZone::__construct(): Unknown or bad timezone () in /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php:43
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: Stack trace:
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: #0 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php(43): DateTimeZone->__construct()
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: #1 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php(241): enter_logfile()
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: #2 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/webinterface/_preload.php(11): php_error_handling()
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: #3 /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/webinterface/index.php(2): require_once('/var/www/vhosts...')
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr: #4 {main}
2021-08-02 21:34:16 | Warning | 5.147.48.78 | mod_fcgid: stderr:   thrown in /var/www/vhosts/skill-ts.de/httpdocs/ranksystem/other/_functions.php on line 43

**Comment by wilkens-florian** [comment]
Ihre Nachricht wurde soeben weitergeleitet.
Bitte beachten sie das diese Nachricht unverbindlich ist.

**Comment by Ultrashadow** [comment]
Ranksystem gibt leider seit geraumer Zeit keine Webseite aus, obiges steht im Error Log

**Comment by Newcomer1989** [comment]
Für den Umzug haben wir einen kleinen Wiki-Beitrag erstellt, was alles zu beachten ist.

https://github.com/Newcomer1989/TSN-Ranksystem/wiki#changed-teamspeak-host--server---mitigation-old-ranksystem

Nach den obigen Meldungen wüde ich speziell auf Punkt "4 ii" tippen, dass der Logpfad nicht mehr stimmt bzw. nicht erreichbar ist.

Ansonsten gelten auf dem neuen System natürlich die Voraussetzungen, wie zuvor. Hier z.B. für Linux
https://ts-ranksystem.com/#linux
