### ISSUE TITLE
Bot startet nicht mehr | Uncaught Error: Call to undefined method ZipArchive

### ISSUE THREAD

**Issue by dakeeper** [Newcomer1989/TSN-Ranksystem#865]
Beschreibung | unterhalb ausfüllen
habe heute versucht den Bot wieder zu starten.
Leider bricht der nach ein paar sekunden anscheinend ab.

2022-01-19 12:44:58.294883   DEBUG     SQL executions needs: 0.00423
2022-01-19 12:44:58.294952   DEBUG     reset_rs needs: 0.00001
2022-01-19 12:44:58.295011   NOTICE    DB Export job(s) started
2022-01-19 12:44:58.295212   NOTICE      Started job 'Datenbank Export'
[19-Jan-2022 12:44:58 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method ZipArchive::setEncryptionName() in /var/www/vhosts/d*******.de/httpdocs/ts3rank/jobs/db_ex_imp.php:123
Stack trace:
#0 /var/www/vhosts/d*******.de/httpdocs/ts3rank/jobs/bot.php(474): db_ex_imp()
#1 /var/www/vhosts/d*******.de/httpdocs/ts3rank/jobs/bot.php(547): run_bot()
#2 {main}
  thrown in /var/www/vhosts/d*******.de/httpdocs/ts3rank/jobs/db_ex_imp.php on line 123
Ranksystem Version | 1.3._19_
Nutzt du TeamSpeak oder TeaSpeak? | Teamspeak

Kann hier jemand helfen?
Wäre echt schade wenn die ganzen Stats weg wären :(

---

**Comment by Newcomer1989** [comment]
Leider fehlen entscheidende Informationen aus der Log-Datei:
- Systemumgebung (Linux / Windows)
- PHP-Version

Ich vermute, dass hier Linux zum Einsatz kommt.

Der Meldung nach würde ich vermuten PHP-ZIP ist zwar installiert, allerdings ist die im Hintergrund verwendete Library veraltet.
Falls PHP-ZIP fehlen sollte, erst einmal dies installieren.
`sudo apt install php-zip`

Es wird `libzip` >= 1.2.0 benötigt.

Das Problem sollte sich im Regelfall lösen, wenn das Hostsystem aktualisiert wird. Im Zweifel die genannte Library gezielt updaten.

**Comment by dakeeper** [comment]
Hallo Newcomer1989, 

danke für deine antwort. Und Sorry wegen der fehlenden informationen.
Ich reiche mal nach:

Systemumgebung ist Linux, Ubuntu 18.04.6 LTS
PHP Version ist 7.4.27
Database Version: 5.5.5-10.5.11-MariaDB-1:10.5.11+maria~bionic
Ranksystem Version: 1.3.19 (on Update-Channel: stable)

libzip ist installiert, aktuellste version.

Ich habe hier nochmal den (meiner meinung nach relevanten) log teil, wobei ich denke das es an
undefined method ZipArchive::setEncryptionName() hakt.

2022-02-03 15:05:26.645670   NONE      
  thrown in /var/www/vhosts/********/httpdocs/ts3rank/jobs/db_ex_imp.php on line 123
#2 {main}
#1 /var/www/vhosts/********/httpdocs/ts3rank/jobs/bot.php(547): run_bot()
#0 /var/www/vhosts/********/httpdocs/ts3rank/jobs/bot.php(474): db_ex_imp()
Stack trace:
[03-Feb-2022 14:52:09 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined method ZipArchive::setEncryptionName() in /var/www/vhosts/********/httpdocs/ts3rank/jobs/db_ex_imp.php:123
2022-02-03 14:52:09.202019   NOTICE      Started job 'Datenbank Export'
2022-02-03 14:52:09.201768   NOTICE    DB Export job(s) started
2022-02-03 14:52:09.201706   DEBUG     reset_rs needs: 0.00001
2022-02-03 14:52:09.201614   DEBUG     SQL executions needs: 0.00626
2022-02-03 14:52:09.195274   DEBUG     update_channel needs: 0.00390

**Comment by Newcomer1989** [comment]
Wir werden demnächst die Version 1.3.20 veröffentlichen. Ein bisschen wird das noch dauern. Dadurch würden deine Änderungen überschrieben.

Bitte dann mal schauen, ob es noch immer zu den genannten Problem kommt. Wenn ja, müssten wir hier mal tiefer einsteigen. Das sollte jedoch grundlegend ein Problem mit der Installation sein, nicht mit dem Bot, hätte ich ganz vorsichtig behauptet.

Ich schließe das Issue bis dahin mal. Wie gesagt: Wenn es erneut auftritt, bitte wieder melden.
